l_english:
 artifact_history_created_desc: "Created by [SelectLocalization( HISTORY_ENTRY.HasActor, HISTORY_ENTRY.GetActor.GetNameNoTooltip, 'UNKNOWN_BENEFACTOR' )] for [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] at [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 artifact_history_stolen_desc: "Stolen by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_given_desc: "Given to [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_inherited_desc: "Inherited by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_conquest_desc: "Taken by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] in a war against [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_taken_in_siege_desc: "Seized by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] after the siege of [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 artifact_history_reforged_desc: "Reforged by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] in [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 artifact_history_discovered_desc: "Discovered by [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal] for [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] at [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 artifact_history_won_in_duel_desc: "Won in duel by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_taken_in_battle_desc: "Taken by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] in the battle of [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 artifact_history_prize_created_desc: "Offered by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] as a [GetActivityType( 'activity_tournament' ).GetName] [prize|E]"

 artifact_history_prize_awarded_desc: "Awarded to [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] as a [contest|E] [prize|E]"

 artifact_history_creator_discovered_desc: "Discovered to have originally been created by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_purchased_desc: "Purchased by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 artifact_history_ransomed_desc: "Ransomed by [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"

 CHARACTER_PAYS_REFORGE_COST: "[CHARACTER.Custom('ShortName')|U] will pay $COST$ to reforge [ARTIFACT.GetName]"
 CHARACTER_PAYS_REPAIR_COST: "[CHARACTER.Custom('ShortName')|U] will pay $COST$ to repair [ARTIFACT.GetName]"

 ARTIFACT_CREATOR: "Creator: [Artifact.GetCreator.GetName]"

 CHARACTER_CANNOT_DECLARE_WAR: "[Character.Custom('ShortNameNoTooltip')|U] cannot currently declare war for this [artifact|e]"

 CHARACTER_CAN_DECLARE_WAR: "[Character.Custom('ShortNameNoTooltip')|U] can declare war for this [artifact|e]"

 CHARACTER_WITHOUT_ROYAL_COURT_COURT_ARTIFACT_TAB: "Since [Character.Custom('ShortName')] [Character.LocalPlayerString( 'have', 'has' )] no [royal_court|e], [Character.Custom('ShortName')] [Character.LocalPlayerString( 'have', 'has' )] nowhere to display these [court_artifacts|e]."